services:
  - type: web
    name: giyim
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DB_PATH
        value: /var/data/veritabani.db
      - key: UPLOAD_DIR
        value: /var/data/uploads
      - key: ADMIN_PANEL_KEY
        generateValue: true
    disk:
      name: giyim-data
      mountPath: /var/data
      sizeGB: 1
